name: ava_luxe
description: Ava Luxe MVP
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # UI + features
  webview_flutter: ^4.8.0
  flutter_tts: ^3.8.5
  share_plus: ^10.1.4
  shared_preferences: ^2.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
