import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:firebase_auth/firebase_auth.dart';
import 'state/app_settings.dart';
import 'state/avatar_model.dart';
import 'screens/auth/sign_in_screen.dart';
import 'screens/home_screen.dart';
import 'firebase_options.dart'; // generated by FlutterFire CLI
import 'package:google_fonts/google_fonts.dart';

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  final settings = AppSettings();
  await settings.load();

  runApp(MultiProvider(
    providers: [
      ChangeNotifierProvider(create: (_) => settings),
      ChangeNotifierProvider(create: (_) => AvatarModel()..load()),
    ],
    child: const AvaLuxeApp(),
  ));
}

class AvaLuxeApp extends StatelessWidget {
  const AvaLuxeApp({super.key});

  @override
  Widget build(BuildContext context) {
    final s = context.watch<AppSettings>();
    return MaterialApp(
      title: 'Ava Luxe',
      theme: ThemeData(
        colorSchemeSeed: const Color(0xFF7C4DFF),
        brightness: s.darkMode ? Brightness.dark : Brightness.light,
        textTheme: GoogleFonts.caveatTextTheme(
          Theme.of(context).textTheme.apply(fontSizeFactor: s.textScale),
        ),
      ),
      home: const AuthGate(),
      debugShowCheckedModeBanner: false,
    );
  }
}

class AuthGate extends StatelessWidget {
  const AuthGate({super.key});

  @override
  Widget build(BuildContext context) {
    return StreamBuilder<User?>(
      stream: FirebaseAuth.instance.authStateChanges(),
      builder: (context, snapshot) {
        if (snapshot.connectionState == ConnectionState.waiting) {
          return const Scaffold(body: Center(child: CircularProgressIndicator()));
        }
        if (snapshot.hasData) {
          return const HomeScreen();
        }
        return const SignInScreen();
      },
    );
  }
}
