name: Build Android APK (Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter 3.22.2
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: stable
          cache: true

      # Generate the missing Android/Gradle scaffolding on the runner
      - name: Generate Android project files
        run: flutter create --platforms=android --project-name ava_luxe .

      - name: Pub get
        run: flutter pub get

      - name: Accept Android licenses
        run: yes | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build release APKs (per ABI)
        run: flutter build apk --release --split-per-abi

      - name: Upload APK artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ava-luxe-apks
          path: build/app/outputs/flutter-apk/*.apk
          if-no-files-found: error
