name: Build Android APK (Flutter)

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          channel: 'stable'
          cache: true

      - name: Create Android platform
        run: flutter create . --platforms=android

      - name: Write google-services.json from secret
        env:
          FIREBASE_ANDROID_JSON: ${{ secrets.FIREBASE_ANDROID_JSON }}
        run: |
          mkdir -p android/app
          printf '%s' "$FIREBASE_ANDROID_JSON" > android/app/google-services.json
          echo "google-services.json written to android/app/"

      - name: flutter pub get
        run: flutter pub get

      - name: Build release APK
        env:
          OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
        run: |
          # if you later want the key at compile time, add:
          # --dart-define=OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
          flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: ava-luxe-apk
          path: build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error
