name: Build Android APK (Flutter)

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: "3.22.2"

      - name: Flutter pub get
        run: flutter pub get

      # If android/ is missing, create it (keeps Gradle versions sane)
      - name: Ensure Android folder exists
        run: |
          if [ ! -d "android" ]; then
            flutter create . --platforms=android
          fi

      # Make sure AndroidX switches are on (safe if already present)
      - name: Ensure AndroidX
        run: |
          echo "android.useAndroidX=true" >> android/gradle.properties
          echo "android.enableJetifier=true" >> android/gradle.properties

      # If you put google-services.json in android/app/, this step is not needed.
      # Just make sure the file is committed.
      - name: Build release APK
        run: flutter build apk --release --dart-define=OPENROUTER_API_KEY=${{ secrets.OPENROUTER_API_KEY }}

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: avaluxe-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
